language: c
dist: bionic
matrix:
  fast_finish: true
  include:
    # OS X Mavericks
    - os: osx
      env: CC_COMPILER=clang CXX_COMPILER=clang++


    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env: CC_COMPILER=gcc-10 CXX_COMPILER=g++-10

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: CC_COMPILER=gcc-9 CXX_COMPILER=g++-9

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CC_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: CC_COMPILER=gcc-7 CXX_COMPILER=g++-7

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CC_COMPILER=gcc-6 CXX_COMPILER=g++-6

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - g++-6-multilib
            - gcc-multilib
      env: CC_COMPILER=gcc-6 CXX_COMPILER=g++-6 MORE_OPTIONS="BUILD_ARCH=32-bit"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CC_COMPILER=gcc-5 CXX_COMPILER=g++-5

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-multilib
      env: CC_COMPILER=gcc-5 CXX_COMPILER=g++-5 MORE_OPTIONS="BUILD_ARCH=32-bit"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/$TRAVIS_DIST/ llvm-toolchain-$TRAVIS_DIST-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
      env: CC_COMPILER=clang-10 CXX_COMPILER=clang++-10

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/$TRAVIS_DIST/ llvm-toolchain-$TRAVIS_DIST-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env: CC_COMPILER=clang-9 CXX_COMPILER=clang++-9

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-$TRAVIS_DIST-8
          packages:
            - clang-8
      env: CC_COMPILER=clang-8 CXX_COMPILER=clang++-8

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-$TRAVIS_DIST-7
          packages:
            - clang-7
      env: CC_COMPILER=clang-7 CXX_COMPILER=clang++-7

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-$TRAVIS_DIST-6.0
          packages:
            - clang-6.0
      env: CC_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-$TRAVIS_DIST-5.0
          packages:
            - clang-5.0
      env: CC_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0


    # Ubuntu 14.04 LTS Server Edition 64 bit
    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-aarch64-linux-gnu
            - g++-aarch64-linux-gnu
      env: QEMU_INTERPRETER=qemu-aarch64-static CC_COMPILER=aarch64-linux-gnu-gcc CXX_COMPILER=aarch64-linux-gnu-g++ MORE_OPTIONS="BUILD_STATIC=1"

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-arm-linux-gnueabi
            - g++-arm-linux-gnueabi
      env: QEMU_INTERPRETER=qemu-arm-static CC_COMPILER=arm-linux-gnueabi-gcc CXX_COMPILER=arm-linux-gnueabi-g++ MORE_OPTIONS="BUILD_STATIC=1"

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: QEMU_INTERPRETER=qemu-ppc64-static CC_COMPILER=powerpc-linux-gnu-gcc CXX_COMPILER=powerpc-linux-gnu-g++ MORE_OPTIONS="MOREFLAGS=-m64 BUILD_STATIC=1 DONT_BUILD_YAPPY=1 DONT_BUILD_DENSITY=1 DONT_BUILD_ZLING=1"

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: QEMU_INTERPRETER=qemu-ppc-static CC_COMPILER=powerpc-linux-gnu-gcc CXX_COMPILER=powerpc-linux-gnu-g++ MORE_OPTIONS="BUILD_STATIC=1 DONT_BUILD_YAPPY=1 DONT_BUILD_DENSITY=1 DONT_BUILD_ZLING=1"

    - dist: trusty
      sudo: required
      env: CC_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - libc6-dev-i386
            - g++-multilib
      env: CC_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8 MORE_OPTIONS="BUILD_ARCH=32-bit"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CC_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env: CC_COMPILER=clang-3.6 CXX_COMPILER=clang++-3.6

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: CC_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: CC_COMPILER=clang-4.0 CXX_COMPILER=clang++-4.0

script:
  - $CC_COMPILER -v
  - $CXX_COMPILER -v
  - make CC=$CC_COMPILER CXX=$CXX_COMPILER $MORE_OPTIONS
  - file ./lzbench
  - $QEMU_INTERPRETER ./lzbench
  - $QEMU_INTERPRETER ./lzbench -eall ./lzbench
